package com.datngoc.wms.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    // --- Hệ thống (System Errors) ---
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),
    VALIDATION_FAILED("VALIDATION_FAILED", HttpStatus.BAD_REQUEST),

    // --- Xác thực & Bảo mật (Auth & Security) ---
    AUTH_FAILED("AUTH_FAILED", HttpStatus.UNAUTHORIZED),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED("ACCESS_DENIED", HttpStatus.FORBIDDEN),

    // --- Nghiệp vụ (Business Errors) ---

    // USER
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    USER_NOT_EXISTED("USER_NOT_EXISTED", HttpStatus.NOT_FOUND),
    USER_NOT_FOUND("USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),

    // ROLE
    ROLE_ALREADY_EXISTS("ROLE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND", HttpStatus.NOT_FOUND),

    // CATEGORY
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND", HttpStatus.NOT_FOUND),
    CATEGORY_ALREADY_EXISTS("CATEGORY_ALREADY_EXISTS", HttpStatus.CONFLICT),
    CATEGORY_CANNOT_MOVE_TO_CHILD("CATEGORY_CANNOT_MOVE_TO_CHILD", HttpStatus.BAD_REQUEST),
    CATEGORY_CANNOT_DELETE_WITH_CHILD("CATEGORY_CANNOT_DELETE_WITH_CHILD", HttpStatus.BAD_REQUEST),
    // PRODUCT
    PRODUCT_NOT_EXISTS("PRODUCT_NOT_EXISTS", HttpStatus.NOT_FOUND),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", HttpStatus.NOT_FOUND),
    SKU_NOT_FOUND("SKU_NOT_FOUND", HttpStatus.NOT_FOUND),
    PRODUCT_ALREADY_EXISTS("PRODUCT_ALREADY_EXISTS", HttpStatus.CONFLICT),

    // INVENTORY & STOCK
    INSUFFICIENT_RESOURCES("INSUFFICIENT_RESOURCES", HttpStatus.BAD_REQUEST),
    STOCK_SHORTAGE("STOCK_SHORTAGE", HttpStatus.BAD_REQUEST),
    SKU_ALREADY_EXISTS("SKU_ALREADY_EXISTS", HttpStatus.CONFLICT),
    OUT_OF_STOCK("OUT_OF_STOCK", HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_IN_WAREHOUSE("PRODUCT_NOT_IN_WAREHOUSE", HttpStatus.NOT_FOUND),

    // UNIT
    UNIT_NOT_FOUND("UNIT_NOT_FOUND", HttpStatus.NOT_FOUND),
    UNIT_ALREADY_EXISTS("UNIT_ALREADY_EXISTS", HttpStatus.CONFLICT),

    // WAREHOUSE & LOCATION
    WAREHOUSE_NOT_EXISTS("WAREHOUSE_NOT_EXISTS", HttpStatus.NOT_FOUND),
    WAREHOUSE_NOT_FOUND("WAREHOUSE_NOT_FOUND", HttpStatus.NOT_FOUND),
    LOCATION_FULL("LOCATION_FULL", HttpStatus.BAD_REQUEST),
    LOCATION_ALREADY_EXISTS("LOCATION_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ORDER_LOCKED("ORDER_LOCKED", HttpStatus.BAD_REQUEST);

    private final String messageKey;
    private final HttpStatus httpStatus;
}